name: ìƒˆë¡œìš´ PR ìƒì„± ì‹œ ìŠ¬ë™ì— ì•Œë¦¼ ë³´ë‚´ê¸°

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ìŠ¬ë™ì— ì•Œë¦¼ ì „ì†¡
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ğŸ†• *ìƒˆë¡œìš´ PRì´ ì‘ì„±ë˜ì—ˆìŠµë‹ˆë‹¤* ğŸ†•"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR ì œëª©:* ${{ github.event.pull_request.title }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "PR í™•ì¸",
                      "emoji": true
                    },
                    "url": "${{ github.event.pull_request.html_url }}",
                    "action_id": "button_click"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}