name: ìƒˆë¡œìš´ ë¦¬ë·° ìƒì„± ì‹œ ìŠ¬ë™ì— ì•Œë¦¼ ë³´ë‚´ê¸°

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: í™˜ê²½ë³€ìˆ˜ ì„¤ì •
        run: |
          BODY=$(echo "${{ github.event.review.body }}" | sed ':a;N;$!ba;s/\r//g;s/\n/\\n/g')
          echo "BODY=$BODY" >> $GITHUB_ENV
          echo "URL=${{ github.event.review.html_url }}" >> $GITHUB_ENV

      - name: ìŠ¬ë™ì— ì•Œë¦¼ ì „ì†¡
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ğŸ’¬ *ìƒˆë¡œìš´ ë¦¬ë·°ê°€ ì‘ì„±ë˜ì—ˆìŠµë‹ˆë‹¤* ğŸ’¬"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*PR ì œëª©:* ${{ github.event.pull_request.title }}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "PR í™•ì¸",
                      "emoji": true
                    },
                    "url": "${{ env.URL }}",
                    "action_id": "button_click"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "\n${{ env.BODY }}"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}